/* (c) 2026 Quake Gaming Nation. All rights reserved. Do not copy or redistribute. */
(function(){for(var s=location.hostname.toLowerCase(),a=["dG9ueWh4Yy5naXRodWIuaW8=","bG9jYWxob3N0","MTI3LjAuMC4x"],i=0;i<a.length;i++)if(atob(a[i])===s)return;var r=atob("aHR0cHM6Ly90b255aHhjLmdpdGh1Yi5pby8="),d=function(){document.title="Quake Gaming Nation";var o=document.body||document.documentElement;o.innerHTML='<div style="position:fixed;inset:0;display:grid;place-items:center;background:#0a0a0a;color:#e9e4d8;font:16px/1.6 monospace;text-align:center;z-index:2147483647"><div><div style="font:bold 34px Impact,sans-serif;color:#f2c014;letter-spacing:1px">QUAKE GAMING NATION</div><p>This only runs on the official site.</p><p><a style="color:#3dff7a" href="'+r+'">'+r+"</a></p></div></div>"};throw document.readyState==="loading"?document.addEventListener("DOMContentLoaded",d):d(),new Error("Quake Gaming Nation: play at "+r)})(),(()=>{"use strict";if(window.CasinoGuides)return;const s={};let a=null;const i=document.createElement("style");i.textContent=`
  .cg-btn { font: inherit; font-weight: 800; font-size: 13px; border: 2px solid #24223a; background: #fff; color: #24223a; border-radius: 99px; padding: 5px 12px; cursor: pointer; margin: 0 0 8px 8px; vertical-align: middle; }
  .cg-btn:hover { background: #24223a; color: #ffcf5a; }
  .cg-ov { position: absolute; inset: 0; z-index: 60; background: #0b0a12b3; display: flex; align-items: center; justify-content: center; padding: 14px; }
  .cg-box { position: relative; width: min(760px, 100%); max-height: 100%; display: flex; flex-direction: column; background: #f4f2ec; color: #1b1a22; border-radius: 14px; box-shadow: 0 24px 60px #000a; overflow: hidden; }
  .cg-head { display: flex; align-items: center; gap: 10px; padding: 12px 16px; background: #24223a; color: #fff; }
  .cg-head h3 { margin: 0; font-size: 18px; color: #fff; } .cg-head span { font-size: 12px; color: #c9c6dd; }
  .cg-head button { margin-left: auto; border: 0; border-radius: 8px; background: #ff5f57; color: #fff; font-weight: 900; padding: 6px 12px; cursor: pointer; font: inherit; font-weight: 900; }
  .cg-toc { display: flex; flex-wrap: wrap; gap: 6px; padding: 10px 16px 0; }
  .cg-toc a { font-size: 12px; font-weight: 800; color: #24223a; background: #fff; border: 1px solid #ddd9cf; border-radius: 99px; padding: 3px 10px; text-decoration: none; cursor: pointer; }
  .cg-toc a:hover { border-color: #24223a; }
  .cg-body { overflow: auto; padding: 6px 18px 18px; font-size: 14px; line-height: 1.55; color: #3b3a44; }
  .cg-body h4 { margin: 18px 0 6px; font-size: 15px; color: #1b1a22; text-transform: uppercase; letter-spacing: .6px; }
  .cg-body p { margin: 6px 0; font-size: 14px; color: #3b3a44; } .cg-body ul, .cg-body ol { margin: 6px 0; padding-left: 20px; } .cg-body li { margin: 3px 0; }
  .cg-body table { width: 100%; border-collapse: collapse; margin: 8px 0; font-size: 13px; background: #fff; border-radius: 8px; overflow: hidden; }
  .cg-body th, .cg-body td { text-align: left; padding: 6px 8px; border-bottom: 1px solid #e6e2d8; } .cg-body th { background: #ebe7dc; font-size: 11px; text-transform: uppercase; letter-spacing: .5px; color: #55536a; }
  .cg-body .num { text-align: right; font-variant-numeric: tabular-nums; }
  .cg-body kbd { font: 700 12px ui-monospace, monospace; background: #fff; border: 1px solid #c9c4b8; border-bottom-width: 2px; border-radius: 5px; padding: 0 5px; }
  .cg-note { background: #fff6dc; border-left: 4px solid #ffcf5a; padding: 8px 12px; border-radius: 0 8px 8px 0; margin: 10px 0; font-size: 13px; }
  .cg-key { display: grid; grid-template-columns: auto 1fr; gap: 4px 12px; margin: 6px 0; } .cg-key b { white-space: nowrap; }`,document.head.appendChild(i);function r(o,e){const f=s[o];if(!f)return;d();const l=f(),p=e&&e.closest&&e.closest(".win, .card")||document.body;p!==document.body&&getComputedStyle(p).position==="static"&&(p.style.position="relative");const n=document.createElement("div");n.className="cg-ov",p===document.body&&(n.style.position="fixed");const g=document.createElement("div");g.innerHTML=l.html;const x=[...g.querySelectorAll("h4")];x.forEach((t,c)=>t.id=`cg-${o}-${c}`),n.innerHTML=`<div class="cg-box" role="dialog" aria-label="${l.title} guide"><div class="cg-head"><h3>${l.icon||"📖"} ${l.title}</h3><span>How to play</span><button class="cg-x">Close ✕</button></div>
    <div class="cg-toc">${x.map((t,c)=>`<a data-to="cg-${o}-${c}">${t.textContent}</a>`).join("")}</div><div class="cg-body">${g.innerHTML}</div></div>`,n.addEventListener("click",t=>{(t.target===n||t.target.closest(".cg-x"))&&d();const c=t.target.closest("[data-to]");if(c){const u=n.querySelector("#"+c.dataset.to);u&&u.scrollIntoView({behavior:"smooth",block:"start"})}}),n.addEventListener("wheel",t=>t.stopPropagation()),n.addEventListener("pointerdown",t=>t.stopPropagation()),p.appendChild(n),a=n}function d(){a&&(a.remove(),a=null)}document.addEventListener("click",o=>{const e=o.target.closest&&o.target.closest("[data-guide]");e&&(o.preventDefault(),r(e.dataset.guide,e))}),window.addEventListener("keydown",o=>{a&&o.key==="Escape"&&(o.preventDefault(),o.stopImmediatePropagation(),d())},!0),window.CasinoGuides={add(o,e){s[o]=e},has:o=>!!s[o],button:(o,e="📖 How to play")=>`<button class="cg-btn" data-guide="${o}" title="Read how this game works before you bet">${e}</button>`,show:r,close:d,get isOpen(){return!!a}}})();